2024-09-01 12:45:04,341 | INFO | "test_challenge" выполнен успешно
2024-09-01 12:45:04,342 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\murad\MyProjects\Module12_development_cycle_support\runner_test_v3.py", line 25, in test_run
    runner2 = rt.Runner('Бегун 2', -11)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\murad\MyProjects\Module12_development_cycle_support\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -11
2024-09-01 12:45:04,346 | WARNING | Неверный тип данных для Runner
Traceback (most recent call last):
  File "C:\Users\murad\MyProjects\Module12_development_cycle_support\runner_test_v3.py", line 12, in test_walk
    runner1 = rt.Runner(12345, 10)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\murad\MyProjects\Module12_development_cycle_support\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
